---
- name: Ensure redis is running
  shell: (docker inspect canvas_redis &> /dev/null && docker start canvas_redis) || docker run --name canvas_redis --net host -d {{ redis_docker_image }} redis-server
